apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-stack-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/pio11oip/argocd-manifests.git"
    targetRevision: main
    path: "environments/dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: shop-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
